id: 358264961233059843
name: DCC
active: true
description: Division Command Center
facility: ALL
name_format_type: first_last_initial
title_type: division
roles:
  - id: 1268392286215999670
    name: Verified
    criteria:
      - conditions:
          - type: all
  - id: 1268396646543134811
    name: OBS
    criteria:
      - conditions:
          - type: rating
            value: OBS
  - id: 1268393449317470352
    name: S1
    criteria:
      - conditions:
          - type: rating
            value: S1
  - id: 1268393499611631659
    name: S2
    criteria:
      - conditions:
          - type: rating
            value: S2
  - id: 1268393529420415146
    name: S3
    criteria:
      - conditions:
          - type: rating
            value: S3
  - id: 1268393645606961172
    name: CPC
    criteria:
      - conditions:
          - type: rating
            value: C1
      - conditions:
          - type: rating
            value: C3
      - conditions:
          - type: rating
            value: I1
      - conditions:
          - type: rating
            value: I3
  - id: 1268393707762225285
    name: ZDC
    criteria:
      - conditions:
          - type: home
            value: ZDC
  - id: 1268393791258103920
    name: ZSE
    criteria:
      - conditions:
          - type: home
            value: ZSE
  - id: 1268393840016883828
    name: ZLC
    criteria:
      - conditions:
          - type: home
            value: ZLC
  - id: 1268393883067355147
    name: ZOA
    criteria:
      - conditions:
          - type: home
            value: ZOA
  - id: 1268393954446151762
    name: ZNY
    criteria:
      - conditions:
          - type: home
            value: ZNY
  - id: 1268394000973565993
    name: ZMP
    criteria:
      - conditions:
          - type: home
            value: ZMP
  - id: 1268394049971294409
    name: ZMA
    criteria:
      - conditions:
          - type: home
            value: ZMA
  - id: 1268394087065718804
    name: ZME
    criteria:
      - conditions:
          - type: home
            value: ZME
  - id: 1268394123438719098
    name: ZLA
    criteria:
      - conditions:
          - type: home
            value: ZLA
  - id: 1268394156372525169
    name: ZKC
    criteria:
      - conditions:
          - type: home
            value: ZKC
  - id: 1268394205529641062
    name: ZJX
    criteria:
      - conditions:
          - type: home
            value: ZJX
  - id: 1268394241323962433
    name: ZID
    criteria:
      - conditions:
          - type: home
            value: ZID
  - id: 1268394285942702213
    name: ZHU
    criteria:
      - conditions:
          - type: home
            value: ZHU
  - id: 1268394321376448564
    name: HCF
    criteria:
      - conditions:
          - type: home
            value: HCF
  - id: 1268394378397876255
    name: ZFW
    criteria:
      - conditions:
          - type: home
            value: ZFW
  - id: 1268394408924020856
    name: ZDV
    criteria:
      - conditions:
          - type: home
            value: ZDV
  - id: 1268394460874539018
    name: ZOB
    criteria:
      - conditions:
          - type: home
            value: ZOB
  - id: 1268394495469158441
    name: ZAU
    criteria:
      - conditions:
          - type: home
            value: ZAU
  - id: 1268394555703824414
    name: ZBW
    criteria:
      - conditions:
          - type: home
            value: ZBW
  - id: 1268394595444850778
    name: ZTL
    criteria:
      - conditions:
          - type: home
            value: ZTL
  - id: 1268394629049483316
    name: ZAN
    criteria:
      - conditions:
          - type: home
            value: ZAN
  - id: 1268394666127265939
    name: ZAB
    criteria:
      - conditions:
          - type: home
            value: ZAB
  - id: 1268394837254733957
    name: ARTCC Staff
    criteria:
      - conditions:
          - type: role
            value: ATM
      - conditions:
          - type: role
            value: DATM
      - conditions:
          - type: role
            value: EC
  - id: 1268395359714021396
    name: NTMO
    criteria:
      - conditions:
          - type: facility_role
            value: ZHQ:DCC
  - id: 1268395731186749524
    name: VATUSA
    criteria:
      - conditions:
          - type: division_staff