id: 477298775455563776
name: ZID
active: true
description: Indy Center
facility: ZID
name_format_type: first_last
title_type: local
roles:
  - id: 896858108054368298
    name: Observer
    criteria:
      - conditions:
          - type: rating
            value: OBS
  - id: 896858107702042655
    name: Student 1
    criteria:
      - conditions:
          - type: rating
            value: S1
  - id: 896858107404255233
    name: Student 2
    criteria:
      - conditions:
          - type: rating
            value: S2
  - id: 896858107051909159
    name: Student 3
    criteria:
      - conditions:
          - type: rating
            value: S3
  - id: 896858105789440041
    name: Controller 1
    criteria:
      - conditions:
          - type: rating
            value: C1
  - id: 896858105567129631
    name: Controller 3
    criteria:
      - conditions:
          - type: rating
            value: C3
  - id: 896858105390977084
    name: Instructor 1
    criteria:
      - conditions:
          - type: rating
            value: I1
  - id: 896858104677924916
    name: Instructor 3
    criteria:
      - conditions:
          - type: rating
            value: I3
  - id: 896858104187220030
    name: Supervisor
    criteria:
      - conditions:
          - type: rating
            value: SUP
  - id: 896858103914561596
    name: Administrator
    criteria:
      - conditions:
          - type: rating
            value: ADM
  - id: 1178168909115969707
    name: Mentor
    criteria:
      - conditions:
          - type: facility_role
            value: ZID:MTR
  - id: 991370038340759593
    name: VATUSA Staff
    criteria:
      - conditions:
          - type: division_staff
  - id: 477496066590375947
    name: Training Staff
    criteria:
      - conditions:
          - type: facility_role
            value: ZID:MTR
      - conditions:
          - type: facility_role
            value: ZID:INS
      - conditions:
          - type: home
            value: ZID
          - type: rating
            value: I1
      - conditions:
          - type: home
            value: ZID
          - type: rating
            value: I3
  - id: 700873587388711012
    name: Ace Team
    criteria:
      - conditions:
          - type: role
            value: ACE
  - id: 477495351838900254
    name: Air Traffic Controller
    criteria:
      - conditions:
          - type: home
            value: ZID
      - conditions:
          - type: visit
            value: ZID
  - id: 1125403438545641564
    name: Member
    criteria:
      - conditions:
          - type: all
            value: true
